# Generated by Django 4.1.11 on 2023-09-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swj', '0002_rename_title_member_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='slug',
            field=models.SlugField(max_length=10, unique_for_date='publish'),
        ),
    ]
