# Generated by Django 4.1.11 on 2023-09-12 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swj', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='title',
            new_name='name',
        ),
    ]
